version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: career_chronicle_developer
      POSTGRES_PASSWORD: career_chronicle_password
      POSTGRES_DB: career_chronicle_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USER: career_chronicle_developer
      DATABASE_PASSWORD: career_chronicle_password
      DATABASE_NAME: career_chronicle_development

volumes:
  postgres_data:
