default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", "career_chronicle-db") %>
  username: <%= ENV.fetch("DATABASE_USER", "career_chronicle_developer") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "career_chronicle_password") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "career_chronicle_development") %>

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: career_chronicle_production
  username: <%= ENV.fetch("DATABASE_USER", "career_chronicle_developer") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "career_chronicle_password") %>
